server:
  port: 9007
spring:
  application:
    name: potato-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.11.129:3306/potato_user?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    database: MySQL
    show‐sql: true
    generate‐ddl: true
  redis:
    host: 192.168.11.129
  rabbitmq:
    host: 192.168.11.129
jwt:
  config:
    key: potato
    ttl: 360000
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true    # 确保模块之间能够跨域访问