server:
  port: 9005
spring:
  application:
    name: potato-advice
  data:
    mongodb:
      host: 192.168.11.132
      port: 27017
      database: advicedb
  redis:
    host: 192.168.11.132
jwt:
  config:
    key: potato
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true    # 确保模块之间能够跨域访问