server:
  port: 9010
spring:
  application:
    name: potato-manager
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.11.132:6868/eureka/
  instance:
    prefer-ip-address: true    # 确保模块之间能够跨域访问
zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    potato-advice:
      path: /advice/**
      serviceId: potato-advice
    potato-gathering:
      path: /gathering/**
      serviceId: potato-gathering
    potato-message:
      path: /message/**
      serviceId: potato-message
    potato-resource:
      path: /site/**
      serviceId: potato-resource
    potato-user:
      path: /**
      serviceId: potato-user
jwt:
  config:
    key: potato
    ttl: 7200000
# 添加ribbon的超时时间设置
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 60000