server:
  port: 9008
spring:
  application:
    name: potato_search
  data:
    elasticsearch:
      cluster-nodes: 192.168.11.132:9300
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.11.132:6868/eureka/
  instance:
    prefer-ip-address: true    # 确保模块之间能够跨域访问