server:
  port: 9004
spring:
  application:
    name: potato-gathering
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.11.132:3306/potato_gathering?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    database: MySQL
    show‐sql: true
    generate‐ddl: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.11.132:6868/eureka/
  instance:
    prefer-ip-address: true    # 确保模块之间能够跨域访问